USE NETFLIX
GO
CREATE
  TABLE dbo.CAT_USER_TYPE
  (
    ID_USER_TYPE   INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    USER_TYPE_NAME VARCHAR (20) ,
    LOAD_DATE      DATETIME
  )
  ON "PRIMARY" TEXTIMAGE_ON 'PRIMARY'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Este valor es la llave primaria, es autoincremental.' ,
'SCHEMA' ,
'dbo' ,
'TABLE' ,
'CAT_USER_TYPE' ,
'COLUMN' ,
'ID_USER_TYPE'
GO
EXEC sp_addextendedproperty 'MS_Description' ,
'Nombre del tipo de usuario' ,
'SCHEMA' ,
'dbo' ,
'TABLE' ,
'CAT_USER_TYPE' ,
'COLUMN' ,
'USER_TYPE_NAME'
GO
CREATE UNIQUE INDEX CAT_USER_TYPE_ID_USER_TYPE_IDX ON dbo.CAT_USER_TYPE
(
  ID_USER_TYPE ASC
)

CREATE TABLE dbo.CAT_USER_TYPE_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,ID_USER_TYPE INTEGER NOT NULL
 ,USER_TYPE_NAME VARCHAR (20)
 ,LOAD_DATE DATETIME
 );

CREATE OR REPLACE TRIGGER dbo.CAT_USER_TYPE_JNtrg
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON dbo.CAT_USER_TYPE for each row 
 Declare 
  rec dbo.CAT_USER_TYPE_JN%ROWTYPE; 
  blank dbo.CAT_USER_TYPE_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ID_USER_TYPE := :NEW.ID_USER_TYPE; 
      rec.USER_TYPE_NAME := :NEW.USER_TYPE_NAME; 
      rec.LOAD_DATE := :NEW.LOAD_DATE; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ID_USER_TYPE := :OLD.ID_USER_TYPE; 
      rec.USER_TYPE_NAME := :OLD.USER_TYPE_NAME; 
      rec.LOAD_DATE := :OLD.LOAD_DATE; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into dbo.CAT_USER_TYPE_JN VALUES rec; 
  END; 
  /