ALTER TABLE dbo.CAT_USER ADD CONSTRAINT CAT_USER_PK PRIMARY KEY CLUSTERED (
ID_USER)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO
ALTER TABLE dbo.CAT_USER ADD CONSTRAINT USERNAME_UQ UNIQUE NONCLUSTERED (
USERNAME)
ON "default"
GO