CREATE DATABASE NETFLIX ON PRIMARY(
  NAME     = 'NETFLIX_Data.MDF',
  FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\NETFLIX_Data.MDF',
  MAXSIZE  = UNLIMITED
)
